# Generated by Django 3.1.7 on 2021-06-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210619_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
